# Site settings
title: Yakun's New Start
email: yakunw.victor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn from the past.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wykvictor.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  wykvictor

# Build settings
markdown: kramdown
# highlighter: true
