# parameters to disable unused package in opencv build

set(BUILD_ANDROID_EXAMPLES OFF CACHE BOOL "")
set(BUILD_FAT_JAVA_LIB OFF CACHE BOOL "")
set(BUILD_JASPER OFF CACHE BOOL "")
set(BUILD_OPENEXR OFF CACHE BOOL "")
set(BUILD_PACKAGE OFF CACHE BOOL "")
set(BUILD_PERF_TESTS OFF CACHE BOOL "")
set(BUILD_PNG OFF CACHE BOOL "")
set(BUILD_TBB OFF CACHE BOOL "")
set(BUILD_TESTS OFF CACHE BOOL "")
set(BUILD_TIFF OFF CACHE BOOL "")
set(BUILD_WITH_DEBUG_INFO OFF CACHE BOOL "")
set(BUILD_opencv_androidcamera OFF CACHE BOOL "")
set(BUILD_opencv_calib3d OFF CACHE BOOL "")
set(BUILD_opencv_contrib OFF CACHE BOOL "")
set(BUILD_opencv_features2d OFF CACHE BOOL "")
set(BUILD_opencv_flann OFF CACHE BOOL "")
set(BUILD_opencv_gpu OFF CACHE BOOL "")
set(BUILD_opencv_java OFF CACHE BOOL "")
set(BUILD_opencv_legacy OFF CACHE BOOL "")
set(BUILD_opencv_ml OFF CACHE BOOL "")
set(BUILD_opencv_nonfree OFF CACHE BOOL "")
set(BUILD_opencv_objdetect OFF CACHE BOOL "")
set(BUILD_opencv_ocl OFF CACHE BOOL "")
set(BUILD_opencv_photo OFF CACHE BOOL "")
set(BUILD_opencv_stitching OFF CACHE BOOL "")
set(BUILD_opencv_ts OFF CACHE BOOL "")
set(BUILD_opencv_video OFF CACHE BOOL "")
set(BUILD_opencv_videostab OFF CACHE BOOL "")


set(CMAKE_C_FLAGS "-fvisibility=hidden " CACHE STRING "")
set(CMAKE_CXX_FLAGS "-fvisibility=hidden " CACHE STRING "")

set(ENABLE_DYNAMIC_CUDA OFF CACHE BOOL "")
set(WITH_CUDA OFF CACHE BOOL "")
set(WITH_CUFFT OFF CACHE BOOL "")
set(WITH_EIGEN OFF CACHE BOOL "")
set(WITH_JASPER OFF CACHE BOOL "")
set(WITH_OPENCL OFF CACHE BOOL "")
set(WITH_OPENEXR OFF CACHE BOOL "")
set(WITH_PNG OFF CACHE BOOL "")
set(WITH_TIFF OFF CACHE BOOL "")

